package com.ibm.rules.decisionservice.pffmonitoreo123_ruleapp.pffmonitoreo123rules;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.17
 * 2016-11-11T18:20:40.615-06:00
 * Generated source version: 2.7.17
 * 
 */
@WebServiceClient(name = "PffMonitoreo123rulesDecisionService", 
                  wsdlLocation = "http://lnxsodm3d.dev.unix.banorte.com:9080/DecisionService/ws/pffMonitoreo123_RuleApp/3.0/pffMonitoreo123rules?WSDL",
                  targetNamespace = "http://www.ibm.com/rules/decisionservice/PffMonitoreo123_RuleApp/PffMonitoreo123rules") 
public class PffMonitoreo123RulesDecisionService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.ibm.com/rules/decisionservice/PffMonitoreo123_RuleApp/PffMonitoreo123rules", "PffMonitoreo123rulesDecisionService");
    public final static QName PffMonitoreo123RuleAppPffMonitoreo123RulesPort = new QName("http://www.ibm.com/rules/decisionservice/PffMonitoreo123_RuleApp/PffMonitoreo123rules", "PffMonitoreo123_RuleAppPffMonitoreo123rulesPort");
    static {
        URL url = null;
        try {
            url = new URL("http://lnxsodm3d.dev.unix.banorte.com:9080/DecisionService/ws/pffMonitoreo123_RuleApp/3.0/pffMonitoreo123rules?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PffMonitoreo123RulesDecisionService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://lnxsodm3d.dev.unix.banorte.com:9080/DecisionService/ws/pffMonitoreo123_RuleApp/3.0/pffMonitoreo123rules?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public PffMonitoreo123RulesDecisionService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PffMonitoreo123RulesDecisionService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PffMonitoreo123RulesDecisionService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PffMonitoreo123RulesDecisionService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PffMonitoreo123RulesDecisionService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PffMonitoreo123RulesDecisionService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns PffMonitoreo123RulesDecisionService
     */
    @WebEndpoint(name = "PffMonitoreo123_RuleAppPffMonitoreo123rulesPort")
    public PffMonitoreo123RulesDecisionService getPffMonitoreo123RuleAppPffMonitoreo123RulesPort() {
        return super.getPort(PffMonitoreo123RuleAppPffMonitoreo123RulesPort, PffMonitoreo123RulesDecisionService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PffMonitoreo123RulesDecisionService
     */
    @WebEndpoint(name = "PffMonitoreo123_RuleAppPffMonitoreo123rulesPort")
    public PffMonitoreo123RulesDecisionService getPffMonitoreo123RuleAppPffMonitoreo123RulesPort(WebServiceFeature... features) {
        return super.getPort(PffMonitoreo123RuleAppPffMonitoreo123RulesPort, PffMonitoreo123RulesDecisionService.class, features);
    }

}
