package com.ibm.rules.decisionservice.pffmonitoreo123_ruleapp.pffmonitoreo123rules;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.17
 * 2016-11-11T18:20:40.543-06:00
 * Generated source version: 2.7.17
 * 
 */
@WebService(targetNamespace = "http://www.ibm.com/rules/decisionservice/PffMonitoreo123_RuleApp/PffMonitoreo123rules", name = "PffMonitoreo123rulesDecisionService")
@XmlSeeAlso({ObjectFactory.class, com.ibm.rules.decisionservice.pffmonitoreo123_ruleapp.pffmonitoreo123rules.param.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PffMonitoreo123RulesDecisionService {

    @WebResult(name = "PffMonitoreo123rulesResponse", targetNamespace = "http://www.ibm.com/rules/decisionservice/PffMonitoreo123_RuleApp/PffMonitoreo123rules", partName = "PffMonitoreo123rulesResponse")
    @WebMethod(operationName = "PffMonitoreo123rules", action = "PffMonitoreo123rules")
    public PffMonitoreo123RulesResponse pffMonitoreo123Rules(
        @WebParam(partName = "PffMonitoreo123rulesRequest", name = "PffMonitoreo123rulesRequest", targetNamespace = "http://www.ibm.com/rules/decisionservice/PffMonitoreo123_RuleApp/PffMonitoreo123rules")
        PffMonitoreo123RulesRequest pffMonitoreo123RulesRequest
    ) throws PffMonitoreo123RulesSoapFault;
}
