
package com.ibm.rules.decisionservice.pffmonitoreo123_ruleapp.pffmonitoreo123rules;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.17
 * 2016-11-11T18:20:40.472-06:00
 * Generated source version: 2.7.17
 */

@WebFault(name = "PffMonitoreo123rulesException", targetNamespace = "http://www.ibm.com/rules/decisionservice/PffMonitoreo123_RuleApp/PffMonitoreo123rules")
public class PffMonitoreo123RulesSoapFault extends Exception {
    
    private com.ibm.rules.decisionservice.pffmonitoreo123_ruleapp.pffmonitoreo123rules.PffMonitoreo123RulesException pffMonitoreo123RulesException;

    public PffMonitoreo123RulesSoapFault() {
        super();
    }
    
    public PffMonitoreo123RulesSoapFault(String message) {
        super(message);
    }
    
    public PffMonitoreo123RulesSoapFault(String message, Throwable cause) {
        super(message, cause);
    }

    public PffMonitoreo123RulesSoapFault(String message, com.ibm.rules.decisionservice.pffmonitoreo123_ruleapp.pffmonitoreo123rules.PffMonitoreo123RulesException pffMonitoreo123RulesException) {
        super(message);
        this.pffMonitoreo123RulesException = pffMonitoreo123RulesException;
    }

    public PffMonitoreo123RulesSoapFault(String message, com.ibm.rules.decisionservice.pffmonitoreo123_ruleapp.pffmonitoreo123rules.PffMonitoreo123RulesException pffMonitoreo123RulesException, Throwable cause) {
        super(message, cause);
        this.pffMonitoreo123RulesException = pffMonitoreo123RulesException;
    }

    public com.ibm.rules.decisionservice.pffmonitoreo123_ruleapp.pffmonitoreo123rules.PffMonitoreo123RulesException getFaultInfo() {
        return this.pffMonitoreo123RulesException;
    }
}
